---
apiVersion: capability.tw/v1alpha1
kind: Platform
metadata:
  name: viator-experiences
  title: Viator Experiences
spec:
  owner: group:member-x
---
apiVersion: capability.tw/v1alpha1
kind: Platform
metadata:
  name: engineering
  title: Engineering
spec:
  owner: user:brew
---
apiVersion: capability.tw/v1alpha1
kind: Platform
metadata:
  name: marketplace-services
  title: Marketplace Services
spec:
  owner: group:vortex
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: post-booking
  title: Post Booking
spec:
  owner: member-x
  platform: viator-experiences
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: pre-trip
  title: Pre-Trip
spec:
  owner: member-x
  capability: post-booking
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: manage-my-bookings
  title: Manage My Bookings
spec:
  owner: member-x
  capability: pre-trip
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: payment
  title: Payment
spec:
  owner: checkout
  type: sub-capability
  capability: manage-my-bookings
  components: 
    - orion
    - bookings
    - accounting-service
    - payout-service
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: cancellation
  title: Cancellation
spec:
  owner: member-x
  type: sub-capability
  capability: manage-my-bookings
  components:
    - orion
    - bookings
    - vrs
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: amend
  title: Amend
spec:
  owner: member-x
  type: sub-capability
  capability: manage-my-bookings
  components:
    - bookings
    - orion
    - demandproduct
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: architecture
  title: Architecture
spec:
  owner: spectre
  platform: engineering
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: service-catalog
  title: Service Catalog
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: tech-strategy
  title: Tech Strategy
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: skeleton-templating
  title: Skeleton Templating
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: distributed-communication
  title: Distributed Communication
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: frontend-frameworks
  title: Frontend Frameworks
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: governance
  title: Governance
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: tech-radar
  title: Tech Radar
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: persistance
  title: Persistance
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: backend-frameworks
  title: Backend Frameworks
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: serverless
  title: Serverless
spec:
  owner: spectre
  capability: architecture
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: merchandising
  title: Merchandising
spec:
  owner: vortex
  platform: marketplace-services
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: destinations
  title: Destinations
spec:
  owner: vortex
  capability: merchandising
  components:
    - demanddestination
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: poi
  title: POIs
spec:
  owner: relevance
  capability: merchandising
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: product-taxonomy
  title: Product Taxonomy
spec:
  owner: vortex
  capability: merchandising
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: search
  title: Search
spec:
  owner: relevance
  capability: merchandising
  components:
    - demandproduct
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: filtering
  title: Filtering
spec:
  owner: relevance
  capability: merchandising
  components:
    - demandproduct
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: product-comparison
  title: Product Comparison
spec:
  capability: merchandising
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: product-reviews
  title: Product Reviews
spec:
  owner: guidance
  capability: merchandising
  components:
    - demandreview
    - demandproduct