---
apiVersion: capability.tw/v1alpha1
kind: Platform
metadata:
  name: viator-experiences
  title: Viator Experiences
spec:
  owner: member-x
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: post-booking
  title: Post Booking
spec:
  owner: member-x
  platform: viator-experiences
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: pre-trip
  title: Pre-Trip
spec:
  owner: member-x
  capability: post-booking
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: manage-my-bookings
  title: Manage My Bookings
spec:
  owner: member-x
  capability: pre-trip
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: payment
  title: Payment
spec:
  owner: checkout
  type: sub-capability
  capability: manage-my-bookings
  components: 
    - orion
    - bookings
    - accounting-service
    - payout-service
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: cancellation
  title: Cancellation
spec:
  owner: member-x
  type: sub-capability
  capability: manage-my-bookings
  components:
    - orion
    - bookings
    - vrs
---
apiVersion: capability.tw/v1alpha1
kind: Capability
metadata:
  name: amend
  title: Amend
spec:
  owner: member-x
  type: sub-capability
  capability: manage-my-bookings
  components:
    - bookings
    - orion