---
apiVersion: functionality.tw/v1alpha1
kind: Platform
metadata:
  name: viator-experiences
  title: Viator Experiences
spec:
  owner: member-x
---
apiVersion: functionality.tw/v1alpha1
kind: Functionality
metadata:
  name: post-booking
  title: Post Booking
spec:
  owner: member-x
  platform: viator-experiences
---
apiVersion: functionality.tw/v1alpha1
kind: Functionality
metadata:
  name: pre-trip
  title: Pre-Trip
spec:
  owner: member-x
  functionality: post-booking
---
apiVersion: functionality.tw/v1alpha1
kind: Functionality
metadata:
  name: manage-my-bookings
  title: Manage My Bookings
spec:
  owner: member-x
  functionality: pre-trip
---
apiVersion: functionality.tw/v1alpha1
kind: Functionality
metadata:
  name: payment
  title: Payment
spec:
  owner: checkout
  functionality: manage-my-bookings
---
apiVersion: functionality.tw/v1alpha1
kind: Functionality
metadata:
  name: cancellation
  title: Cancellation
spec:
  owner: member-x
  functionality: manage-my-bookings
---
apiVersion: functionality.tw/v1alpha1
kind: Functionality
metadata:
  name: amend
  title: Amend
spec:
  owner: member-x
  functionality: manage-my-bookings
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: orion
spec:
  type: website
  lifecycle: production
  owner: guests
  functionalities:
    - cancellation
    - amend
    - payment
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bookings
spec:
  type: service
  lifecycle: production
  owner: member-x
  functionalities:
    - amend
    - cancellation
    - payment
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payout-service
spec:
  type: service
  lifecycle: production
  owner: guests
  functionalities:
    - payment
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accounting-service
spec:
  type: service
  lifecycle: production
  owner: guests
  functionalities:
    - payment
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vrs
spec:
  type: website
  lifecycle: production
  owner: guests
  functionalities:
    - cancellation