---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: leo
  title: Leonardo
spec:
  memberOf: [member-x,checkout]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: member-x
  title: Member X
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: checkout
  title: Checkout
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guidance
  title: Guidance Team
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: spectre
  title: Spectre
spec:
  type: team
  children: []
